### ISSUE TITLE
Sequential Job / Branch-Level takes you a 404 page (branch missing?)

### ISSUE THREAD

**Issue by stonehz** [CircleCI-Public/circleci-demo-workflows#13]
The readme takes you here: https://github.com/CircleCI-Public/circleci-demo-workflows/tree/sequential-branch-filter.
same for main document here: https://circleci.com/docs/2.0/tutorials/

**Comment by zzak** [comment]
Hey @stonehz,

Thanks for your report.

It was accidentally deleted in #12.

Should be OK now, let us know if you see anything different.
