### ISSUE TITLE
workspace-forwarding example is broken

### ISSUE THREAD

**Issue by smiller171** [CircleCI-Public/circleci-demo-workflows#6]
When I try to use the workspace-forwarding example, I get the following error in the `checkout_code` job:

```
Error locating workspace root directory: stat ~/alumni-network: no such file or directory
```

You have this functionality documented differently in several places, and none of them are functional.

**Comment by zzak** [comment]
Hello @smiller171,

Thank you for your report.

I have been seeing that issue as well, and think there was some confusion about workspace paths when I wrote this. Sorry about that, please bear with me while I figure this out and will close this issue once the build is fixed.
